from pathlib import Path
import re

p = Path('index.html')
s = p.read_text(encoding='utf-8')

# Version label
s = s.replace('蓝投一码呼 V0.2 演示原型', '蓝投一码呼 V0.3 演示原型')
s = s.replace('蓝投一码呼 · V0.2', '蓝投一码呼 · V0.3')
s = s.replace('文登蓝投 · 社区居民服务演示原型', '文登蓝投 · 社区居民服务演示原型 V0.3')

# PC/header shell only. Resident/staff mini-program body remains untouched.
new_top = r'''function top(content){var r=role(),isPc=(r==='hub'||r==='work'||r==='group'),tabs=[['hub','演示导航'],['resident-home','居民小程序'],['work-center','工单中心'],['staff-tasks','工作人员'],['group-dashboard','集团监管']];var t=tabs.map(function(x){var on=(r==='hub'&&x[0]==='hub')||x[0].indexOf(r)===0;return '<button class="'+(on?'on':'')+'" onclick="go(\''+x[0]+'\')">'+x[1]+'</button>'}).join('');return '<div class="topbar '+(isPc?'baseTop':'')+'"><div class="brand"><div class="brandmark">'+icon('home')+'</div><span>蓝投一码呼 · V0.3</span></div><div class="roleTabs">'+t+'</div><button class="ghost" onclick="resetDemo()">重置演示</button></div>'+content}'''
s = re.sub(r'function top\(content\)\{.*?\}\nfunction pc', new_top + '\nfunction pc', s, count=1, flags=re.S)

new_pc = r'''function pc(content){var r=role();var n=r==='group'?[['group-dashboard','运营驾驶舱','chart'],['group-trace','工单穿透','eye']]:[['work-center','工单中心','order'],['work-detail','工单详情','report'],['work-dispatch','受理派单','team']];var current=n.filter(function(x){return location.hash==='#'+x[0]})[0]||n[0];var nav=n.map(function(x){return '<div class="sideItem '+(location.hash==='#'+x[0]?'on':'')+'" onclick="go(\''+x[0]+'\')">'+icon(x[2])+'<span>'+x[1]+'</span></div>'}).join('');var org=r==='group'?'蓝投集团运营管理中心':'蓝海嘉园物业服务中心';return top('<div class="shell"><aside class="sidebar"><div class="sideLabel">当前组织</div><div class="sideItem orgItem">'+icon('home')+'<span>'+org+'</span></div><div class="sideLabel">业务导航</div>'+nav+'<div class="sideLabel">演示工单</div><div class="sideTicket"><div class="tiny">'+D.id+'</div><div class="strong small" style="margin:5px 0">公共区域漏水</div><span class="pill '+(D.state===0?'orange':D.state>=5?'green':'')+'">'+statusNames[D.state]+'</span></div></aside><section class="workspace"><div class="multiTabs"><span class="pcTab">首页</span><span class="pcTab on">'+current[1]+'</span><span class="tabTools">×</span></div><main class="main">'+content+'</main></section></div>')}'''
s = re.sub(r'function pc\(content\)\{.*?\}\nfunction phone', new_pc + '\nfunction phone', s, count=1, flags=re.S)
s = s.replace("function hub(){return top('<div class=\"main\">", "function hub(){return top('<div class=\"main hubMain\">")

marker = '/* 手机端视觉 */'
if 'BaseFream PC 风格覆盖' not in s:
    css = r'''/* BaseFream PC 风格覆盖：仅作用于PC壳层与演示导航，不改变小程序内部样式 */
.baseTop{height:50px;background:#EAF2FF;border-bottom:0;padding:0 12px 0 14px;box-shadow:none}
.baseTop .brand{gap:8px;font-size:14px;color:#1E293B}.baseTop .brandmark{width:30px;height:30px;border-radius:5px;background:#026AFF;box-shadow:none}.baseTop .brandmark svg{width:17px;height:17px}
.baseTop .roleTabs{gap:2px;background:rgba(255,255,255,.62);padding:2px;border-radius:4px;border:1px solid rgba(144,176,218,.28)}.baseTop .roleTabs button{padding:6px 11px;border-radius:3px;font-size:12px;color:#475569}.baseTop .roleTabs button.on{color:#026AFF;background:#fff;box-shadow:0 1px 4px rgba(34,79,134,.10)}.baseTop .ghost{border:1px solid #C9DCF5;background:rgba(255,255,255,.72);color:#475569;border-radius:4px;padding:6px 10px;font-size:12px}
.shell{grid-template-columns:210px 1fr;min-height:calc(100vh - 50px);background:#EAF2FF}.sidebar{background:linear-gradient(180deg,#EAF2FF 0%,#C0DDFD 100%);border-right:0;padding:12px 10px;box-shadow:inset -1px 0 rgba(100,142,195,.08)}
.sideLabel{font-size:11px;color:#71849C;padding:11px 10px 5px;font-weight:500}.sideItem{padding:9px 10px;border-radius:4px;margin:2px 0;color:#334155;font-size:13px;gap:9px;transition:.12s}.sideItem svg{width:17px;height:17px}.sideItem:hover{background:rgba(255,255,255,.45);color:#026AFF}.sideItem.on{background:#fff;color:#026AFF;font-weight:600;box-shadow:0 2px 8px rgba(58,102,157,.10)}.sideItem.orgItem{background:rgba(255,255,255,.42);color:#334155;font-weight:600;border:1px solid rgba(255,255,255,.45)}
.sideTicket{background:rgba(255,255,255,.62);border:1px solid rgba(255,255,255,.7);border-radius:5px;padding:11px;color:#475569}.workspace{min-width:0;background:#EAF2FF;display:flex;flex-direction:column}.multiTabs{height:36px;display:flex;align-items:flex-end;gap:3px;padding:0 12px;background:#EAF2FF;border-bottom:1px solid rgba(141,176,218,.22)}.pcTab{height:30px;padding:7px 13px;background:rgba(255,255,255,.46);border-radius:4px 4px 0 0;font-size:11px;color:#64748B;border:1px solid rgba(166,193,226,.32);border-bottom:0}.pcTab.on{background:#fff;color:#026AFF;font-weight:600}.tabTools{margin-left:auto;color:#8A99AA;font-size:13px;padding:0 7px 7px}
.shell .main{padding:14px 16px 18px;min-width:0}.shell .pageHead{align-items:center;min-height:40px}.shell .pageHead h1{font-size:20px;font-weight:600;color:#1E293B}.shell .sub{font-size:11px;color:#718096;margin-top:3px}.shell .card{background:#fff;border:0;border-radius:6px;padding:15px;box-shadow:0 1px 4px rgba(28,64,109,.07)}.shell .grid{gap:12px}.shell .mt{margin-top:12px}.shell .sectionTitle{font-size:14px;font-weight:600;color:#1E293B;margin-bottom:11px;padding-bottom:9px;border-bottom:1px solid #EEF2F7}
.shell .filter{border:1px solid #D7E0EB;background:#fff;padding:6px 10px;border-radius:4px;color:#536275;font-size:11px}.shell .filter:hover{border-color:#8AB8F5;color:#026AFF}.shell .filter.active{background:#026AFF;border-color:#026AFF;color:#fff;font-weight:500}.shell .btn{background:#026AFF;border-radius:4px;padding:7px 11px;font-weight:500;font-size:12px;box-shadow:none}.shell .btn.light{background:#EAF2FF;color:#026AFF;border:1px solid #BFD8FA}.shell .btn.white{background:#fff;color:#475569;border:1px solid #D7E0EB}.shell .pill{border-radius:3px;padding:3px 7px;font-size:10px}
.shell .kpi{min-height:64px}.shell .kpiNum{font-size:26px;font-weight:650;color:#1E293B;letter-spacing:-.4px}.shell .kpiLabel{font-size:11px;color:#7B8798}.shell .ico{width:40px;height:40px;border-radius:5px;background:#EAF2FF;color:#026AFF}.shell .ico svg{width:20px;height:20px}.shell .tableWrap{border:1px solid #EEF2F6;border-radius:4px}.shell .table th,.shell .table td{padding:10px 9px;border-bottom:1px solid #EEF2F6;font-size:12px}.shell .table th{font-size:11px;font-weight:500;color:#667085;background:#F7F9FC}.shell .table tr:hover td{background:#F7FBFF}.shell .avatar{border-radius:4px;background:#EAF2FF;color:#026AFF}.shell .progress{height:6px;background:#EDF2F7}.shell .progress i{background:#026AFF}
.shell .chart{height:196px}.shell .bar i{background:linear-gradient(180deg,#72ACFA,#026AFF);border-radius:4px 4px 1px 1px}.shell .map{border-radius:5px;background:linear-gradient(145deg,#F4F8FF,#EAF2FF)}.shell .building{border-radius:4px;box-shadow:0 1px 4px rgba(28,73,122,.08)}.shell .timeline{border-left-color:#C9DAEF}.shell .tl.done:before{background:#026AFF;border-color:#026AFF}
.hubMain{background:#EAF2FF;min-height:calc(100vh - 50px);padding:16px}.hubMain .hubHero{background:#fff;color:#334155;border-radius:6px;padding:22px 24px;border-left:4px solid #026AFF;box-shadow:0 1px 4px rgba(28,64,109,.07)}.hubMain .hubHero h1{font-size:24px;color:#1E293B}.hubMain .hubHero .pill{background:#EAF2FF!important;color:#026AFF!important;border-radius:3px!important}.hubMain .card{border:0;border-radius:6px;padding:15px;box-shadow:0 1px 4px rgba(28,64,109,.07)}.hubMain .grid{gap:12px}.hubMain .mt{margin-top:12px}.hubMain .ico{border-radius:5px;background:#EAF2FF;color:#026AFF}.hubMain .roleCard:hover{transform:translateY(-1px);box-shadow:0 4px 12px rgba(28,64,109,.10)}.hubMain .sectionTitle{font-size:14px;font-weight:600}.hubMain .kpiNum{font-size:26px;font-weight:650}
'''
    s = s.replace(marker, css + '\n' + marker, 1)

p.write_text(s, encoding='utf-8')
print('BaseFream PC style applied to index.html')
